type: release
name: r2deploy
version: 0.1
description: Release 2 deployment configuration
ion: 0.0.1
apps:
  ##################################
  # CORE SERVICES
  # Bootstrapper app performs initializations
  ##################################

  - name: bootstrap
    version: 0.1
    processapp: [bootstrap, ion.core.bootstrap_service, BootstrapService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: bootstrap
    config:
      level: datastore

  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: bootstrap
    config:
      level: directory

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]

  - name: bootstrap
    config:
      level: resource_registry

  - name: identity_management
    version: 0.1
    processapp: [identity_management, ion.services.coi.identity_management_service, IdentityManagementService]

  - name: bootstrap
    config:
      level: identity_management

  - name: org_management
    version: 0.1
    processapp: [org_management, ion.services.coi.org_management_service, OrgManagementService]

  - name: bootstrap
    config:
      level: org_management

  - name: exchange_management
    version: 0.1
    processapp: [exchange_management, ion.services.coi.exchange_management_service, ExchangeManagementService]

  - name: bootstrap
    config:
      level: exchange_management

  ##################################
  # HIGHER LEVEL SERVICES - TODO: CORRECT ORDER NEEDS TO BE FIGURED OUT ONCE IMPLEMENTATION HAS BEEN COMPLETED
  ##################################

  ##### COI SERVICES
  - name: agent_management
    version: 0.1
    processapp: [agent_management, ion.services.coi.agent_management_service, AgentManagementService]

  - name: conversation_management
    version: 0.1
    processapp: [conversation_management, ion.services.coi.conversation_management_service, ConversationManagementService]

  - name: object_management
    version: 0.1
    processapp: [object_management, ion.services.coi.object_management_service, ObjectManagementService]

  - name: policy_management
    version: 0.1
    processapp: [policy_management, ion.services.coi.policy_management_service, PolicyManagementService]

  - name: resource_management
    version: 0.1
    processapp: [resource_management, ion.services.coi.resource_management_service, ResourceManagementService]

  - name: service_management
    version: 0.1
    processapp: [service_management, ion.services.coi.service_management_service, ServiceManagementService]

  - name: state_repository
    version: 0.1
    processapp: [state_repository, ion.services.coi.state_repository_service, StateRepositoryService]

  - name: service_gateway
    version: 0.1
    processapp: [service_gateway, ion.services.coi.service_gateway_service, ServiceGatewayService]

  #### CEI Services
  - name: epu_management
    version: 0.1
    processapp: [epu_management, ion.services.cei.epu_management_service, EpuManagementService]

  - name: execution_engine_management
    version: 0.1
    processapp: [execution_engine_management, ion.services.cei.execution_engine_management_service, ExecutionEngineManagementService]

  - name: process_dispatcher
    version: 0.1
    processapp: [process_dispatcher, ion.services.cei.process_dispatcher_service, ProcessDispatcherService]

  - name: provisioner
    version: 0.1
    processapp: [provisioner, ion.services.cei.provisioner_service, ProvisionerService]

  - name: taskable_resource_management
    version: 0.1
    processapp: [taskable_resource_management, ion.services.cei.taskable_resource_management_service, TaskableResourceManagementService]

  - name: taskable_resource_planner
    version: 0.1
    processapp: [taskable_resource_planner, ion.services.cei.taskable_resource_planner_service, TaskableResourcePlannerService]


  #### DM Services
  - name: pubsub_management
    version: 0.1
    processapp: [pubsub_management, ion.services.dm.distribution.pubsub_management_service, PubsubManagementService]

  - name: ingestion_management
    version: 0.1
    processapp: [ingestion_management, ion.services.dm.ingestion.ingestion_management_service, IngestionManagementService]

  - name: transform_management
    version: 0.1
    processapp: [transform_management, ion.services.dm.transformation.transform_management_service, TransformManagementService]

  - name: dataset_management
    version: 0.1
    processapp: [dataset_management, ion.services.dm.inventory.dataset_management_service, DatasetManagementService]

#  - name: data_retriever_service
#    version: 0.1
#    processapp: [data_retriever_service, ion.services.dm.inventory.dataset_management_service, DataRetrieverService]
        
  - name: index_management
    version: 0.1
    processapp: [index_management, ion.services.dm.inventory.index_management_service, IndexManagementService]

#  - name: catalog_management
#    version: 0.1
#    processapp: [catalog_management, ion.services.dm.presentation.catalog_management_service, CatalogManagementService]

#  - name: discovery
#    version: 0.1
#    processapp: [discovery, ion.services.dm.presentation.discovery_service, DiscoveryService]

#  - name: preservation_management
#    version: 0.1
#    processapp: [preservation_management, ion.services.dm.preservation.preservation_management_service, PreservationManagementService]


  ##### SA SERVICES
#  - name: data_acquisition_management
#    version: 0.1
#    processapp: [data_acquisition_management, ion.services.sa.data_acquisition_management.data_acquisition_management_service, DataAcquisitionManagementService]
#
##  - name: instrument_agent
##    version: 0.1
##    processapp: [instrument_agent, ion.services.sa.instrument_management.instrument_agent_service, InstrumentAgentService]
#
#  - name: data_product_management
#    version: 0.1
#    processapp: [data_product_management, ion.services.sa.data_product_management.data_product_management_service, DataProductManagementService]
#
#  - name: data_process_management
#    version: 0.1
#    processapp: [data_process_management, ion.services.sa.data_process_management.data_process_management_service, DataProcessManagementService]
#
#  - name: instrument_management_service
#    version: 0.1
#    processapp: [instrument_management_service, ion.services.sa.instrument_management.instrument_management_service, InstrumentManagementService]
#
#  - name: marine_facility_management
#    version: 0.1
#    processapp: [marine_facility_management, ion.services.sa.marine_facility_management_service.marine_facility_management_service, MarineFacilityManagementService]


  ##### AS SERVICES
  - name: visualization_workflow_management
    version: 0.1
    processapp: [visualization_workflow_management, ion.services.ans.visualization_workflow_management_service, VisualizationWorkflowManagementService]
